# Generated by Django 5.1.6 on 2025-03-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='host',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='answer_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='question_assigned',
            field=models.IntegerField(default=0),
        ),
    ]
