# Generated by Django 5.1.6 on 2025-03-01 05:52

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamesession_answer_received_and_more'),
        ('quiz', '0001_initial'),
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionnaire'),
        ),
        migrations.CreateModel(
            name='GameAttempts',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('user_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionnaire')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
        ),
    ]
