# Generated by Django 5.1.6 on 2025-03-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_host_gamesession_questionnaire_gameattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='session_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
