# Generated by Django 5.1.6 on 2025-03-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameattempts_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelink',
            name='session',
        ),
    ]
