# Generated by Django 5.1.6 on 2025-03-01 07:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesession_session_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameattempts',
            old_name='user_answer',
            new_name='user_response',
        ),
        migrations.AddField(
            model_name='gameattempts',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='gameattempts',
            name='attempt_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameattempts',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
