# Generated by Django 5.1.6 on 2025-03-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gamelink_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelink',
            name='session',
            field=models.ForeignKey(default='0195505caf2676c58d525a713c5dab96', on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
        ),
    ]
