# Generated by Django 5.1.6 on 2025-03-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gamelink_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvitee',
            name='session',
        ),
    ]
