# Generated by Django 5.1.6 on 2025-03-01 16:27

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_gameinvitee_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitee',
            name='session',
            field=models.ForeignKey(default=uuid6.uuid7, on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
        ),
    ]
