# Generated by Django 5.1.6 on 2025-03-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_gameattempts_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameattempts',
            old_name='user_id',
            new_name='user',
        ),
    ]
